### ISSUE TITLE
Offline, make sure the device is powered on.

### ISSUE THREAD

**Issue by Jovink** [RobinBol/io.everythingsmart#1]
Hi Robin,
After installation my device appears offline. On Home Assistant it is still online. 
It use the latest firmware 2023.5.5.. I have reset Homey and the sensor as well. 
See my report as well 40c5ddcf-933e-49e2-b30c-0a97f381f778

**Comment by RobinBol** [comment]
Hi! Thank you for submitting your issue and providing the diagnostic. I can see you are running Homey Pro (Early 2023) v10.0.0-rc.110. This firmware version has an issue with mDNS discovery, which my app uses to connect to the device. This issue has been resolved in v10.0.0-rc.111 (or higher) and is currently available in the Experimental channel. Enable experimental updates on your Homey or wait for it to become stable. I believe that will fix your issue. If not, please re-open this issue!

**Comment by Jovink** [comment]
Sorry Robin, also after installing the experimental update the same result. I PTP of Homey Pro and and EP1 as well 
32f67ff4-a6cc-4858-b435-c85ffe57420a

**Comment by RobinBol** [comment]
Ah, I see you have enabled encryption in the ESPHome firmware, is that correct? Homey seems to be able to connect to your EP1 now, but as it doesn't have the password it fails on the encryption.

**Comment by Jovink** [comment]
Maybe because I installed in in Home Assistant. I have removed the encryption, and now it works. Thank you.
