### ISSUE TITLE
No zone activity and No mmwave

### ISSUE THREAD

**Issue by Torhopmark** [RobinBol/io.everythingsmart#2]
Hi.
I have Just installer my presence sensor, and i have som problems with it. First, it does not seem to register Any alarm for mmwave sensor on the homey app. But when activating the led indikator for mmwave, it register on the led. 

Second, it does not want to trigger zone activity in the app, so it limmits the flows.

Whats wrong?

**Comment by RobinBol** [comment]
Hi @Torhopmark , what is the firmware version of your device? (see device settings in Homey) Do you also have these issues when adding the device to HomeAssistant? (if you use that as well).

**Comment by Torhopmark** [comment]
Firmware version is 8.1.6
I do not use homeassistant, only Homey Pro.

**Comment by RobinBol** [comment]
I meant firmware version of your EP1.

**Comment by Torhopmark** [comment]
In the advanced setting, i can only find "project version" 1.1.6, and "epshome version" 2023.7.1

Tor Erling Hopmark

8. aug. 2023 kl. 08:19 skrev Robin Bolscher ***@***.***>:

﻿

I meant firmware version of your EP1.

**Comment by RobinBol** [comment]
I tried to reproduce by updating my EP1 to the same version, but it seems to work fine. Are you able to run this Homey app on the command line? If so, you could add env.json (see env.example.json) to enable logging to check what happens when you trigger motion.

**Comment by Torhopmark** [comment]
I’m not exactly sure what you mean with that. I would need a tutorial of how to do that.

Mvh
Tor Erling Hopmark

9. aug. 2023 kl. 19:04 skrev Robin Bolscher ***@***.***>:

﻿

I tried to reproduce by updating my EP1 to the same version, but it seems to work fine. Are you able to run this Homey app on the command line? If so, you could add env.json (see env.example.json) to enable logging to check what happens when you trigger motion.

**Comment by RobinBol** [comment]
Never mind, I actually have the same issue as you after updating firmware on the EP1 but just overlooked it before. It is due to a breaking change in the firmware of the EP1. I have created an issue (https://github.com/EverythingSmartHome/everything-presence-one/issues/99) and published a fix in v1.0.5 of the Everything Smart app for Homey. Please let me know if that resolves your issue as it did for me.

**Comment by Torhopmark** [comment]
The update fixed the issue👍🏻 thank you!

Mvh
Tor Erling Hopmark

9. aug. 2023 kl. 19:55 skrev Robin Bolscher ***@***.***>:

﻿

Never mind, I actually have the same issue as you after updating firmware on the EP1 but just overlooked it before. It is due to a breaking change in the firmware of the EP1. I have created an issue (EverythingSmartHome/everything-presence-one#99<https://github.com/EverythingSmartHome/everything-presence-one/issues/99>) and published a fix in v1.0.5 of the Everything Smart app for Homey. Please let me know if that resolves your issue as it did for me.

**Comment by RobinBol** [comment]
Thanks for reporting!
