### ISSUE TITLE
Everything Lite

### ISSUE THREAD

**Issue by ratcliffeg** [RobinBol/io.everythingsmart#3]
Any chance to add the Lite version as well? Happy to help test (I have 3)

**Comment by RobinBol** [comment]
I am about to receive a Lite, so I hope to find time soon to add support for it. Wil post here when I have a test version available.

**Comment by RobinBol** [comment]
@ratcliffeg just published v1.0.1 to test which includes a basic driver for the Lite (https://homey.app/a/io.everythingsmart/test/), please let me know how this works for you! There are no settings implemented yet by the way. Feel free to contribute :)

**Comment by TimoSoof** [comment]
Thanks!
Seems to work oke.
Only thing i noticed: after installing and working oke i replaced him in another room so power off and power on then he did not came back (the red alert remained).

**Comment by RobinBol** [comment]
I managed to reproduce your issue, v1.1.1 should resolve it! Also added the max_distance setting to configure the mmWave distance.
