### ISSUE TITLE
Help with Device setup

### ISSUE THREAD

**Issue by briandonna** [RobinBol/io.everythingsmart#8]
I would like to know if anyone knows how to set this device up? The instructions from EP1 are for smarting's, and home assistant, so, I do not know how to do the initial firmware update or the Wi-Fi setup. Can you help with some instructions on this? Any help would be greatly appreciated! :)

**Comment by RobinBol** [comment]
Hi @briandonna , thanks for your question. When adding the EP1 to Homey you will see pair instructions containing the information you request:

<img width="416" alt="Screenshot 2024-06-06 at 08 51 11" src="https://github.com/RobinBol/io.everythingsmart/assets/5762579/722c7e07-e22d-4d78-bdd3-1c7cc0db6220">

Hope this helps!

**Comment by briandonna** [comment]
Hi Robin,

No that did not help, but I was able to figure it out.

What I was having a problem with was I did not know how to get to the Wi-Fi portion of the device so I could add my Wi-Fi information, but I was able to figure that out. You have to go Everything Presence website and act as if you are going to add it to Home Assistant and just stop the process after you finish the Wi-Fi configuration, you can then install your app and connect and the app will find the sensor. 

I think this would be good information for future app installers to have if you would like to add this information to your app somewhere.
